import { Car } from "lucide-react-native";
import Categories from "../screens/tabs/Categories";
import AdminScreen from "../screens/admin";
import PaymentMethodsScreen from "../screens/payment-methods";
import OrderDetailsScreen from "../screens/product/OrderDetails";
import PdfPreview from "../screens/product/Invoice";
import AdminOrderDetailsScreen from "../screens/product/AdminOrderDetails";

export const StackNames = {

    // Auth Stack
    AuthStack: 'AuthStack',
    LoginScreen: 'LoginScreen',
    SignUpScreen: 'SignUpScreen',
    CreatePasswordScreen: 'CreatePasswordScreen',
    CreateMPINScreen: 'CreateMPINScreen',
    ValidationOTPEmailPhone: 'ValidationOTPEmailPhone',
    ForgotPasswordScreen: 'ForgotPasswordScreen',
    ForgotMPINScreen: 'ForgotMPINScreen',
    MPINLOGIN: 'MPinLogin',

    // Main App Stack
    MainAppStack: 'MainAppStack',
    Home: 'Home',
    Categories: 'Categories',
    Explore: 'Explore',
    Search: 'Search',
    Profile: 'Profile',
    WorkoutScreen: 'Workout',
    SubscriptionScreen: 'Subscription Plans',
    SupportScreen: 'Support & Help',
    Onboarding: 'Onboarding',

    // Other Screens
    NotFoundScreen: 'NotFoundScreen',
    ProfileCompletionScreen: 'Profile Completion',
    ProductDetails: 'Product Detail',
    Cart: 'Cart',
    Checkout: 'Checkout',
    OrderSuccess: 'Order Success',
    Orders: 'Orders',
    OrderDetails: 'Order Details',
    AddressManagement: 'AddressManagement',
    AddEditAddress: 'AddEditAddress',
    PaymentMethods: 'PaymentMethods',
    AddPaymentMethod: 'AddPaymentMethod',
    EditProfile: 'EditProfile',
    ChangePassword: 'ChangePassword',
    Wishlist: 'Wishlist',
    Reviews: 'Reviews',
    TermsAndConditions: 'TermsAndConditions',
    PrivacyPolicy: 'PrivacyPolicy',
    AboutUs: 'AboutUs',
    FAQ: 'FAQ',
    LocationSelector: 'LocationSelector',
    MapScreen: 'MapScreen',
    LanguageSelection: 'LanguageSelection',
    CurrencySelection: 'CurrencySelection',
    FilterScreen: 'FilterScreen',
    SortOptions: 'SortOptions',
    SearchResults: 'SearchResults',
    CategoryProducts: 'CategoryProducts',
    SubCategoryProducts: 'SubCategoryProducts',
    BrandProducts: 'BrandProducts',
    FlashSales: 'FlashSales',
    BestSellers: 'BestSellers',
    NewArrivals: 'NewArrivals',
    FeaturedProducts: 'FeaturedProducts',
    CartSummary: 'CartSummary',
    OrderTracking: 'OrderTracking',
    ReturnRequest: 'ReturnRequest',
    CancelOrder: 'CancelOrder',
    NewsletterSubscription: 'NewsletterSubscription',
    PushNotificationsSettings: 'PushNotificationsSettings',
    DarkModeSettings: 'DarkModeSettings',
    DataUsageSettings: 'DataUsageSettings',
    LinkedAccounts: 'LinkedAccounts',
    SocialMediaLinks: 'SocialMediaLinks',
    FeedbackAndSuggestions: 'FeedbackAndSuggestions',
    AppVersionInfo: 'AppVersionInfo',
    AdminScreen: 'Admin',
    WishListScreen: 'Wishlist',
    AddressesScreen: 'Address',
    NotificationsScreen: 'Notifications',
    SettingsScreen: 'Settings',
    PaymentMethodsScreen: 'Payment Methods',
    OrderDetailsScreen: 'Order Details',
    PdfPreview: 'PdfPreview',
    AdminOrderDetailsScreen: 'Order Details(Admin)',
}